### ISSUE TITLE
cache Expires の指定

### ISSUE THREAD

**Issue by vipzero** [yotsugi-vip/vip-splat3-schedule#1]
ブラウザ側が有効にするかわからないけど
Cache-Control か Expires 古いのが表示されないようにできそう

**Comment by yotsugi-vip** [comment]
今の作りだとビルド毎に生成した画像に直接アクセスしてるのでキャッシュの制御ができない
next.jsで作ってるからapi経由でで配布するようにすればヘッダ制御できるはず？

**Comment by vipzero** [comment]
あなるほど
`vercel.json` で画像だけ `max-age` 追加するとか
https://vercel.com/docs/concepts/projects/project-configuration#headers

**Comment by yotsugi-vip** [comment]
[Image Optimization with Vercel](https://vercel.com/docs/concepts/image-optimization#caching)
> アプリケーションを再デプロイしても、画像キャッシュは無効にならないことに注意してください。ただし、画像を変更した場合はキャッシュが無効になり、新しい画像が提供されます。

とのこと。
スケジュール更新毎に画像を生成してるのでキャッシュは無効にされるはず。

**Comment by vipzero** [comment]
そのキャッシュはエッジが提供する静的ファイルの話のような気がする？
Next.js の image タグで生成されたサイト側に追加される最適化で
ブラウザ側はサーバー側の画像ファイルを再取得すべきか(キャッシュを使うべきか)ヘッダでしか判断しようがないけどそれもついてるのかな

ただ専ブラなどが直画像のヘッダの有効期限をちゃんと見てリロードするのかはわからん

**Comment by vipzero** [comment]
ごめんもう今帰ってきてる `cache-control: public, max-age=0, must-revalidate` で適切っぽくて
今使ってる専ブラのプレビューの仕様の問題か
